feat/refactor: add tests for external software
SysBioChalmers/RAVEN pull request #377
Opened 2021-11-02 11:01 UTC by simas232

### Main improvements in this PR:
- refactor:
  - `testBlast` and `testDiamond` now use a small multi-FASTA file containing 4 protein sequences instead of the genome-scale yeast proteome (tutorial/sce.fa). Due to the negligible difference between quick and full checks, the input parameter `fullCheck` was removed from both functions.

- feat:
  - added testing functions and testing files for HMMER, MAFFT and CD-HIT binaries
  - `checkInstallation`: functionality check for BLAST+, DIAMOND, HMMER, CD-HIT and MAFFT is now done by calling their corresponding test functions

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the [development guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/DevGuidelines).
- [X] Selected `devel` as a target branch
- [ ] If needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about this PR

2021-11-02 13:00 UTC, edkerk commented
Would it make sense to wrap these testing functions in [unit tests](https://se.mathworks.com/help/matlab/matlab_prog/write-function-based-unit-tests.html), similar as done in 8dd899d7efe9ae7e367ecc03de560ad38036b633?

2021-11-02 13:50 UTC, simas232 commented
It definitely would, just these functions need assertion checks for expected output. While this would likely mean that we would need to update expected output when the binaries are updated (no problem here), I wonder if it is somehow possible to force e.g. `blastp.exe... OK` printed output as required by `checkInstallation`. Perhaps one parent function would be able to tackle this, if it is not possible to get the convenient output from testing functions themselves.

2021-11-03 13:53 UTC, edkerk commented
I suppose if a test fails because of not matching output after a binary update, then that would be a trigger to potentially update the expected output if required. So sounds good!

2021-12-02 08:47 UTC, edkerk commented on external/getBlast.m
> +end
```suggestion
delete([tmpDB filesep 'tmpDB*']);
```

2021-12-02 08:48 UTC, edkerk commented on external/getBlast.m
> +    end
```suggestion
    delete([tmpDB filesep 'tmpDB*']);
```

2021-12-02 08:49 UTC, edkerk commented on external/getDiamond.m
> +end
```suggestion
delete([tmpDB filesep 'tmpDB*']);
```

2021-12-02 08:49 UTC, edkerk commented on external/getDiamond.m
> +    end
```suggestion
    delete([tmpDB filesep 'tmpDB*']);
```

2021-12-02 08:50 UTC, edkerk commented on installation/checkInstallation.m
> +end
```suggestion
end

```

2021-12-02 08:55 UTC, edkerk requested changes
The MAFFT test fails on my PC, but it did so before as well, so most likely a problem with my installation (Windows 10, MATLAB R2021a).

The tests involve an MD5 check, does this mean that the hash should be (possibly) be updated if the binary is updated?

2021-12-03 06:08 UTC, simas232 commented
@edkerk, please use the [the very latest MAFFT version](https://mafft.cbrc.jp/alignment/software/mafft-7.490-win64-signed.zip) to do the testing on your machine. Once this PR is merged I will create another PR for external software updates.

I have not checked whether MD5 hashes change between different versions, but we will see if it does in PR involving software updates soon anyway.

2021-12-03 19:20 UTC, edkerk approved these changes

2021-12-03 19:25 UTC, merged